In [62]:
pip install feedparser

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 4.8 MB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=f6424f29d55c58d7b88ba6f36e1bd9a511ac0f0a7ed6a47299dedaff7b3fdd69
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

In [68]:
import feedparser
import pandas as pd

rss_url = "https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml"

feed = feedparser.parse(rss_url)

data = []

for entry in feed.entries:
    data.append({
        "title": entry.title,
        "link": entry.link,
        "published": entry.published,
        "summary": entry.summary
    })

df = pd.DataFrame(data)

print(df.head())

                                               title  \
0  Iran-backed Houthis claim missile launch on Is...
1  How the US and Israel are making the Islamic r...
2  Iran-US war latest: Yemen’s Tehran-backed Hout...
3  Iran-backed Houthis fire missile at Israel fro...
4  Iran-backed Houthis claim first missile launch...

                                                link  \
0  https://www.theglobeandmail.com/business/artic...
1  https://www.aljazeera.com/opinions/2026/3/28/h...
2  https://www.independent.co.uk/news/world/middl...
3  https://www.nbcnews.com/world/iran/iran-backed...
4  https://www.newsday.com/news/nation/iran-us-is...

                       published  \
0  Sat, 28 Mar 2026 11:23:02 GMT
1  Sat, 28 Mar 2026 11:12:32 GMT
2  Sat, 28 Mar 2026 10:15:44 GMT
3  Sat, 28 Mar 2026 10:12:01 GMT
4  Sat, 28 Mar 2026 09:27:05 GMT

                                             summary
0  <div><img src="https://www.theglobeandmail.com...
1  <div><img src="https://www.aljazeera.com/wp-co...
2  <div><img src="https://static.independent.co.u...
3  <div><img src="https://media-cldnry.s-nbcnews....
4  <div><img src="https://cdn.newsday.com/ace/c:Y...

In [69]:
print(feed)

{'bozo': False, 'entries': [{'title': 'Iran-backed Houthis claim missile launch on Israel as war in Middle East intensifies', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Iran-backed Houthis claim missile launch on Israel as war in Middle East intensifies'}, 'summary': '<div><img src="https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&amp;width=1200&amp;height=800&amp;quality=80&amp;smart=true" style="width: 100%;" /><div>Israel struck Iran’s nuclear facilities hours after threatening to ‘escalate and expand’ its campaign against Tehran</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&amp;width=1200&amp;height=800&amp;quality=80&amp;smart=true" style="width: 100%;" /><div>Israel struck Iran’s nuclear facilities hours after threatening to ‘escalate and expand’ its campaign against Tehran</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.theglobeandmail.com/business/article-iran-war-houthis-israel-us/'}], 'link': 'https://www.theglobeandmail.com/business/article-iran-war-houthis-israel-us/', 'id': '6b348ded5e01785895fc5a65b1eaa629', 'guidislink': False, 'authors': [{'name': 'Samy Magdy, Aamer Madhani And Jon Gambrell'}], 'author': 'Samy Magdy, Aamer Madhani And Jon Gambrell', 'author_detail': {'name': 'Samy Magdy, Aamer Madhani And Jon Gambrell'}, 'published': 'Sat, 28 Mar 2026 11:23:02 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=11, tm_min=23, tm_sec=2, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&width=1200&height=800&quality=80&smart=true'}]}, {'title': 'How the US and Israel are making the Islamic republic stronger', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'How the US and Israel are making the Islamic republic stronger'}, 'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&amp;quality=80" style="width: 100%;" /><div>The war is feeding into a theological narrative of martyrdom and sacrifice that is helping maintain the Islamic Republic</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&amp;quality=80" style="width: 100%;" /><div>The war is feeding into a theological narrative of martyrdom and sacrifice that is helping maintain the Islamic Republic</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.aljazeera.com/opinions/2026/3/28/how-the-us-and-israel-are-making-the-islamic-republic'}], 'link': 'https://www.aljazeera.com/opinions/2026/3/28/how-the-us-and-israel-are-making-the-islamic-republic', 'id': 'be85d72974405faa33356574cd23a73f', 'guidislink': False, 'authors': [{'name': 'Hossein Dabbagh'}], 'author': 'Hossein Dabbagh', 'author_detail': {'name': 'Hossein Dabbagh'}, 'published': 'Sat, 28 Mar 2026 11:12:32 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=11, tm_min=12, tm_sec=32, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&quality=80'}]}, {'title': 'Iran-US war latest: Yemen’s Tehran-backed Houthi rebels launch first missile attack on Israel since war began', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Iran-US war latest: Yemen’s Tehran-backed Houthi rebels launch first missile attack on Israel since war began'}, 'summary': '<div><img src="https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&amp;height=800&amp;crop=1200:800" style="width: 100%;" /><div>Rebel group’s involvement risks broadening and prolonging a war that has entered its fifth week</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&amp;height=800&amp;crop=1200:800" style="width: 100%;" /><div>Rebel group’s involvement risks broadening and prolonging a war that has entered its fifth week</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.independent.co.uk/news/world/middle-east/iran-us-war-live-updates-trump-israel-houthis-hormuz-b2947546.html'}], 'link': 'https://www.independent.co.uk/news/world/middle-east/iran-us-war-live-updates-trump-israel-houthis-hormuz-b2947546.html', 'id': '201b93d77702c18220f85eff0a7d695d', 'guidislink': False, 'authors': [{'name': 'Maira Butt'}], 'author': 'Maira Butt', 'author_detail': {'name': 'Maira Butt'}, 'published': 'Sat, 28 Mar 2026 10:15:44 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=10, tm_min=15, tm_sec=44, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&height=800&crop=1200:800'}]}, {'title': 'Iran-backed Houthis fire missile at Israel from Yemen, risking further escalation', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Iran-backed Houthis fire missile at Israel from Yemen, risking further escalation'}, 'summary': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg" style="width: 100%;" /><div>The Houthis, Tehran’s proxy militia based in Yemen, carry the potential to disrupt shipping in the Red Sea, a critical artery for global trade.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg" style="width: 100%;" /><div>The Houthis, Tehran’s proxy militia based in Yemen, carry the potential to disrupt shipping in the Red Sea, a critical artery for global trade.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.nbcnews.com/world/iran/iran-backed-houthis-fire-missile-israel-yemen-risking-escalation-rcna265581'}], 'link': 'https://www.nbcnews.com/world/iran/iran-backed-houthis-fire-missile-israel-yemen-risking-escalation-rcna265581', 'id': 'efe1f113447689a489a96f2b073da92f', 'guidislink': False, 'authors': [{'name': 'Freddie Clayton'}], 'author': 'Freddie Clayton', 'author_detail': {'name': 'Freddie Clayton'}, 'published': 'Sat, 28 Mar 2026 10:12:01 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=10, tm_min=12, tm_sec=1, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg'}]}, {'title': 'Iran-backed Houthis claim first missile launch on Israel as war in the Mideast intensifies', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Iran-backed Houthis claim first missile launch on Israel as war in the Mideast intensifies'}, 'summary': '<div><img src="https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280" style="width: 100%;" /><div>Iranian-backed Houthi rebels have claimed a missile launch toward Israel, their first since the war in the Middle East started.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280" style="width: 100%;" /><div>Iranian-backed Houthi rebels have claimed a missile launch toward Israel, their first since the war in the Middle East started.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.newsday.com/news/nation/iran-us-israel-trump-lebanon-march-28-2026-l13129'}], 'link': 'https://www.newsday.com/news/nation/iran-us-israel-trump-lebanon-march-28-2026-l13129', 'id': '400f699b14b3cb49959419a01aef73e3', 'guidislink': False, 'authors': [{'name': 'The Associated Press'}], 'author': 'The Associated Press', 'author_detail': {'name': 'The Associated Press'}, 'published': 'Sat, 28 Mar 2026 09:27:05 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=9, tm_min=27, tm_sec=5, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280'}]}, {'title': 'No end to war in sight after one month as Iran squeezes global economy', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'No end to war in sight after one month as Iran squeezes global economy'}, 'summary': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg" style="width: 100%;" /><div>The world is now facing price rises and perhaps even shortages for energy and food that are already baked in — and that’s if the conflict ended tomorrow.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg" style="width: 100%;" /><div>The world is now facing price rises and perhaps even shortages for energy and food that are already baked in — and that’s if the conflict ended tomorrow.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.nbcnews.com/world/iran/one-month-iran-squeezes-global-economy-rcna265279'}], 'link': 'https://www.nbcnews.com/world/iran/one-month-iran-squeezes-global-economy-rcna265279', 'id': '7a9a02c6ec3b5551e4bcd66d58b8d65c', 'guidislink': False, 'authors': [{'name': 'Alexander Smith'}], 'author': 'Alexander Smith', 'author_detail': {'name': 'Alexander Smith'}, 'published': 'Sat, 28 Mar 2026 08:26:39 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=26, tm_sec=39, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg'}]}, {'title': 'US-Israel war on Iran: What’s happening on day 29 of attacks?', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'US-Israel war on Iran: What’s happening on day 29 of attacks?'}, 'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440" style="width: 100%;" /><div>Tensions continue to rise with Iran warning a \'heavy price\' will be paid after Israeli air attacks.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440" style="width: 100%;" /><div>Tensions continue to rise with Iran warning a \'heavy price\' will be paid after Israeli air attacks.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.aljazeera.com/news/2026/3/28/iran-war-what-is-happening-on-day-29-of-us-israel-attacks'}], 'link': 'https://www.aljazeera.com/news/2026/3/28/iran-war-what-is-happening-on-day-29-of-us-israel-attacks', 'id': '2a10c2d3af1f3e16e828d002a4932199', 'guidislink': False, 'authors': [{'name': 'Elizabeth Melimopoulos'}], 'author': 'Elizabeth Melimopoulos', 'author_detail': {'name': 'Elizabeth Melimopoulos'}, 'published': 'Sat, 28 Mar 2026 08:17:54 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=17, tm_sec=54, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440'}]}, {'title': 'The Iran War Is Testing Israel’s Special Relationship with the US', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'The Iran War Is Testing Israel’s Special Relationship with the US'}, 'summary': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg" style="width: 100%;" /><div>Israel’s unity on Iran could prove a liability, Australia runs a social media experiment on minors, and Hyrox is the latest addictive fitness craze.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg" style="width: 100%;" /><div>Israel’s unity on Iran could prove a liability, Australia runs a social media experiment on minors, and Hyrox is the latest addictive fitness craze.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.bloomberg.com/news/newsletters/2026-03-28/the-iran-war-is-testing-israel-s-special-relationship-with-the-us'}], 'link': 'https://www.bloomberg.com/news/newsletters/2026-03-28/the-iran-war-is-testing-israel-s-special-relationship-with-the-us', 'id': '85c56c5d3de6ee5b2ebb4eaf8dc602e0', 'guidislink': False, 'authors': [{'name': 'Kira Bindrim'}], 'author': 'Kira Bindrim', 'author_detail': {'name': 'Kira Bindrim'}, 'published': 'Sat, 28 Mar 2026 08:00:01 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=0, tm_sec=1, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg'}]}, {'title': 'Yemen’s Houthis claim responsibility for a missile attack on Israel', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Yemen’s Houthis claim responsibility for a missile attack on Israel'}, 'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630" style="width: 100%;" /><div>This is a breaking news story.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630" style="width: 100%;" /><div>This is a breaking news story.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.aljazeera.com/news/2026/3/28/yemens-houthis-claim-responsibility-for-a-missile-attack-on-israel-2'}], 'link': 'https://www.aljazeera.com/news/2026/3/28/yemens-houthis-claim-responsibility-for-a-missile-attack-on-israel-2', 'id': 'd086bf67733f514b946cd90877cf24bc', 'guidislink': False, 'authors': [{'name': 'Al Jazeera'}], 'author': 'Al Jazeera', 'author_detail': {'name': 'Al Jazeera'}, 'published': 'Sat, 28 Mar 2026 07:30:45 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=7, tm_min=30, tm_sec=45, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630'}]}, {'title': 'Houthis Enter War and Say Attacks on Iran, Hezbollah Must Stop', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Houthis Enter War and Say Attacks on Iran, Hezbollah Must Stop'}, 'summary': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg" style="width: 100%;" /><div>The Houthis said they had launched ballistic missiles at Israel and would continue operations until strikes on Iran and its proxy militant groups such as Hezbollah in Lebanon stop.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg" style="width: 100%;" /><div>The Houthis said they had launched ballistic missiles at Israel and would continue operations until strikes on Iran and its proxy militant groups such as Hezbollah in Lebanon stop.</div></div>'}, 'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.bloomberg.com/news/articles/2026-03-28/houthis-enter-war-and-say-attacks-on-iran-hezbollah-must-stop'}], 'link': 'https://www.bloomberg.com/news/articles/2026-03-28/houthis-enter-war-and-say-attacks-on-iran-hezbollah-must-stop', 'id': '1b65ffd56c00259062376b2b02582f71', 'guidislink': False, 'authors': [{'name': 'Dana KhraicheKateryna Kadabashy'}], 'author': 'Dana KhraicheKateryna Kadabashy', 'author_detail': {'name': 'Dana KhraicheKateryna Kadabashy'}, 'published': 'Sat, 28 Mar 2026 07:29:02 GMT', 'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=7, tm_min=29, tm_sec=2, tm_wday=5, tm_yday=87, tm_isdst=0), 'media_content': [{'medium': 'image', 'url': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg'}]}, {'title': 'Iran War Live Updates: Iranian Strike on Saudi Base Injures 12 U.S. Troops, Officials Say', 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': 'Iran War Live Updates: Iranian Strike on Saudi Base Injures 12 U.S. Troops, Officials Say'}, 'summary': '<div><img src="https://static01.nyt.com/images/2026/03/28/multimedia/28israel-iran-promo-lgpf/28israel-iran-promo-lgpf-videoSixteenByNine3000.jpg" style="width: 100%;" /><div>The attack was one of the most serious breaches of American defenses since the war began on Feb. 28. Israel and Iran launched new strikes at each other on Saturday.</div></div>', 'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml', 'value': '<div><img src="https://static01.nyt.com/images/2026/03/28/multimedia/28israel-iran-promo-lgpf/28israel-iran-promo-lgpf-videoSixteenByNine3000.jpg" style="width: 100%;" /><div>The attack was one of the most serious breaches of American defenses since the war began on Feb. 28. Israel and Iran launched new strikes at each other on Saturd

In [70]:
feed.entries

[{'title': 'Iran-backed Houthis claim missile launch on Israel as war in Middle East intensifies',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Iran-backed Houthis claim missile launch on Israel as war in Middle East intensifies'},
  'summary': '<div><img src="https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&amp;width=1200&amp;height=800&amp;quality=80&amp;smart=true" style="width: 100%;" /><div>Israel struck Iran’s nuclear facilities hours after threatening to ‘escalate and expand’ its campaign against Tehran</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&amp;width=1200&amp;height=800&amp;quality=80&amp;smart=true" style="width: 100%;" /><div>Israel struck Iran’s nuclear facilities hours after threatening to ‘escalate and expand’ its campaign against Tehran</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.theglobeandmail.com/business/article-iran-war-houthis-israel-us/'}],
  'link': 'https://www.theglobeandmail.com/business/article-iran-war-houthis-israel-us/',
  'id': '6b348ded5e01785895fc5a65b1eaa629',
  'guidislink': False,
  'authors': [{'name': 'Samy Magdy, Aamer Madhani And Jon Gambrell'}],
  'author': 'Samy Magdy, Aamer Madhani And Jon Gambrell',
  'author_detail': {'name': 'Samy Magdy, Aamer Madhani And Jon Gambrell'},
  'published': 'Sat, 28 Mar 2026 11:23:02 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=11, tm_min=23, tm_sec=2, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://www.theglobeandmail.com/resizer/v2/2DWSEJQ4QRDFJD6KDIT2F5MEJ4.jpg?auth=23a692759d71d5c627c75ebb7e8ec4613607bb6bae1f3ca28dfcd263cfec40b4&width=1200&height=800&quality=80&smart=true'}]},
 {'title': 'How the US and Israel are making the Islamic republic stronger',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'How the US and Israel are making the Islamic republic stronger'},
  'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&amp;quality=80" style="width: 100%;" /><div>The war is feeding into a theological narrative of martyrdom and sacrifice that is helping maintain the Islamic Republic</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&amp;quality=80" style="width: 100%;" /><div>The war is feeding into a theological narrative of martyrdom and sacrifice that is helping maintain the Islamic Republic</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.aljazeera.com/opinions/2026/3/28/how-the-us-and-israel-are-making-the-islamic-republic'}],
  'link': 'https://www.aljazeera.com/opinions/2026/3/28/how-the-us-and-israel-are-making-the-islamic-republic',
  'id': 'be85d72974405faa33356574cd23a73f',
  'guidislink': False,
  'authors': [{'name': 'Hossein Dabbagh'}],
  'author': 'Hossein Dabbagh',
  'author_detail': {'name': 'Hossein Dabbagh'},
  'published': 'Sat, 28 Mar 2026 11:12:32 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=11, tm_min=12, tm_sec=32, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-01T030622Z_1511753267_RC2FVJA0O9ER_RTRMADP_3_IRAN-CRISIS-KHAMENEI-1772343904_2b8917-1774691670.jpg?resize=1200,630&quality=80'}]},
 {'title': 'Iran-US war latest: Yemen’s Tehran-backed Houthi rebels launch first missile attack on Israel since war began',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Iran-US war latest: Yemen’s Tehran-backed Houthi rebels launch first missile attack on Israel since war began'},
  'summary': '<div><img src="https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&amp;height=800&amp;crop=1200:800" style="width: 100%;" /><div>Rebel group’s involvement risks broadening and prolonging a war that has entered its fifth week</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&amp;height=800&amp;crop=1200:800" style="width: 100%;" /><div>Rebel group’s involvement risks broadening and prolonging a war that has entered its fifth week</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.independent.co.uk/news/world/middle-east/iran-us-war-live-updates-trump-israel-houthis-hormuz-b2947546.html'}],
  'link': 'https://www.independent.co.uk/news/world/middle-east/iran-us-war-live-updates-trump-israel-houthis-hormuz-b2947546.html',
  'id': '201b93d77702c18220f85eff0a7d695d',
  'guidislink': False,
  'authors': [{'name': 'Maira Butt'}],
  'author': 'Maira Butt',
  'author_detail': {'name': 'Maira Butt'},
  'published': 'Sat, 28 Mar 2026 10:15:44 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=10, tm_min=15, tm_sec=44, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://static.independent.co.uk/2026/03/27/14/31/LEBANON-ISRAEL-IRAN-US-WAR-bi2xamv0.jpeg?width=1200&height=800&crop=1200:800'}]},
 {'title': 'Iran-backed Houthis fire missile at Israel from Yemen, risking further escalation',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Iran-backed Houthis fire missile at Israel from Yemen, risking further escalation'},
  'summary': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg" style="width: 100%;" /><div>The Houthis, Tehran’s proxy militia based in Yemen, carry the potential to disrupt shipping in the Red Sea, a critical artery for global trade.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg" style="width: 100%;" /><div>The Houthis, Tehran’s proxy militia based in Yemen, carry the potential to disrupt shipping in the Red Sea, a critical artery for global trade.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.nbcnews.com/world/iran/iran-backed-houthis-fire-missile-israel-yemen-risking-escalation-rcna265581'}],
  'link': 'https://www.nbcnews.com/world/iran/iran-backed-houthis-fire-missile-israel-yemen-risking-escalation-rcna265581',
  'id': 'efe1f113447689a489a96f2b073da92f',
  'guidislink': False,
  'authors': [{'name': 'Freddie Clayton'}],
  'author': 'Freddie Clayton',
  'author_detail': {'name': 'Freddie Clayton'},
  'published': 'Sat, 28 Mar 2026 10:12:01 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=10, tm_min=12, tm_sec=1, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260328-houthis-1-nd-c07443.jpg'}]},
 {'title': 'Iran-backed Houthis claim first missile launch on Israel as war in the Mideast intensifies',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Iran-backed Houthis claim first missile launch on Israel as war in the Mideast intensifies'},
  'summary': '<div><img src="https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280" style="width: 100%;" /><div>Iranian-backed Houthi rebels have claimed a missile launch toward Israel, their first since the war in the Middle East started.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280" style="width: 100%;" /><div>Iranian-backed Houthi rebels have claimed a missile launch toward Israel, their first since the war in the Middle East started.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.newsday.com/news/nation/iran-us-israel-trump-lebanon-march-28-2026-l13129'}],
  'link': 'https://www.newsday.com/news/nation/iran-us-israel-trump-lebanon-march-28-2026-l13129',
  'id': '400f699b14b3cb49959419a01aef73e3',
  'guidislink': False,
  'authors': [{'name': 'The Associated Press'}],
  'author': 'The Associated Press',
  'author_detail': {'name': 'The Associated Press'},
  'published': 'Sat, 28 Mar 2026 09:27:05 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=9, tm_min=27, tm_sec=5, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://cdn.newsday.com/ace/c:YWE2ZjMwZmUtZWY3OC00:OGRlZmRiOWUtOGM0ZS00/landscape/1280'}]},
 {'title': 'No end to war in sight after one month as Iran squeezes global economy',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'No end to war in sight after one month as Iran squeezes global economy'},
  'summary': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg" style="width: 100%;" /><div>The world is now facing price rises and perhaps even shortages for energy and food that are already baked in — and that’s if the conflict ended tomorrow.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg" style="width: 100%;" /><div>The world is now facing price rises and perhaps even shortages for energy and food that are already baked in — and that’s if the conflict ended tomorrow.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.nbcnews.com/world/iran/one-month-iran-squeezes-global-economy-rcna265279'}],
  'link': 'https://www.nbcnews.com/world/iran/one-month-iran-squeezes-global-economy-rcna265279',
  'id': '7a9a02c6ec3b5551e4bcd66d58b8d65c',
  'guidislink': False,
  'authors': [{'name': 'Alexander Smith'}],
  'author': 'Alexander Smith',
  'author_detail': {'name': 'Alexander Smith'},
  'published': 'Sat, 28 Mar 2026 08:26:39 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=26, tm_sec=39, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2026-03/260327-iran-mb-1510-d93aee.jpg'}]},
 {'title': 'US-Israel war on Iran: What’s happening on day 29 of attacks?',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'US-Israel war on Iran: What’s happening on day 29 of attacks?'},
  'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440" style="width: 100%;" /><div>Tensions continue to rise with Iran warning a \'heavy price\' will be paid after Israeli air attacks.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440" style="width: 100%;" /><div>Tensions continue to rise with Iran warning a \'heavy price\' will be paid after Israeli air attacks.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.aljazeera.com/news/2026/3/28/iran-war-what-is-happening-on-day-29-of-us-israel-attacks'}],
  'link': 'https://www.aljazeera.com/news/2026/3/28/iran-war-what-is-happening-on-day-29-of-us-israel-attacks',
  'id': '2a10c2d3af1f3e16e828d002a4932199',
  'guidislink': False,
  'authors': [{'name': 'Elizabeth Melimopoulos'}],
  'author': 'Elizabeth Melimopoulos',
  'author_detail': {'name': 'Elizabeth Melimopoulos'},
  'published': 'Sat, 28 Mar 2026 08:17:54 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=17, tm_sec=54, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://www.aljazeera.com/wp-content/uploads/2026/03/2026-03-21T204856Z_1871802228_RC249KA13C55_RTRMADP_3_IRAN-CRISIS-TEHRAN-STRIKE-1774672571.jpg?resize=1920,1440'}]},
 {'title': 'The Iran War Is Testing Israel’s Special Relationship with the US',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'The Iran War Is Testing Israel’s Special Relationship with the US'},
  'summary': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg" style="width: 100%;" /><div>Israel’s unity on Iran could prove a liability, Australia runs a social media experiment on minors, and Hyrox is the latest addictive fitness craze.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg" style="width: 100%;" /><div>Israel’s unity on Iran could prove a liability, Australia runs a social media experiment on minors, and Hyrox is the latest addictive fitness craze.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.bloomberg.com/news/newsletters/2026-03-28/the-iran-war-is-testing-israel-s-special-relationship-with-the-us'}],
  'link': 'https://www.bloomberg.com/news/newsletters/2026-03-28/the-iran-war-is-testing-israel-s-special-relationship-with-the-us',
  'id': '85c56c5d3de6ee5b2ebb4eaf8dc602e0',
  'guidislink': False,
  'authors': [{'name': 'Kira Bindrim'}],
  'author': 'Kira Bindrim',
  'author_detail': {'name': 'Kira Bindrim'},
  'published': 'Sat, 28 Mar 2026 08:00:01 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=8, tm_min=0, tm_sec=1, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iGFcMREgm5fI/v0/1200x800.jpg'}]},
 {'title': 'Yemen’s Houthis claim responsibility for a missile attack on Israel',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Yemen’s Houthis claim responsibility for a missile attack on Israel'},
  'summary': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630" style="width: 100%;" /><div>This is a breaking news story.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630" style="width: 100%;" /><div>This is a breaking news story.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.aljazeera.com/news/2026/3/28/yemens-houthis-claim-responsibility-for-a-missile-attack-on-israel-2'}],
  'link': 'https://www.aljazeera.com/news/2026/3/28/yemens-houthis-claim-responsibility-for-a-missile-attack-on-israel-2',
  'id': 'd086bf67733f514b946cd90877cf24bc',
  'guidislink': False,
  'authors': [{'name': 'Al Jazeera'}],
  'author': 'Al Jazeera',
  'author_detail': {'name': 'Al Jazeera'},
  'published': 'Sat, 28 Mar 2026 07:30:45 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=7, tm_min=30, tm_sec=45, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://www.aljazeera.com/wp-content/uploads/2020/09/breaking-news@2x.png?resize=1200,630'}]},
 {'title': 'Houthis Enter War and Say Attacks on Iran, Hezbollah Must Stop',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Houthis Enter War and Say Attacks on Iran, Hezbollah Must Stop'},
  'summary': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg" style="width: 100%;" /><div>The Houthis said they had launched ballistic missiles at Israel and would continue operations until strikes on Iran and its proxy militant groups such as Hezbollah in Lebanon stop.</div></div>',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': '<div><img src="https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg" style="width: 100%;" /><div>The Houthis said they had launched ballistic missiles at Israel and would continue operations until strikes on Iran and its proxy militant groups such as Hezbollah in Lebanon stop.</div></div>'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.bloomberg.com/news/articles/2026-03-28/houthis-enter-war-and-say-attacks-on-iran-hezbollah-must-stop'}],
  'link': 'https://www.bloomberg.com/news/articles/2026-03-28/houthis-enter-war-and-say-attacks-on-iran-hezbollah-must-stop',
  'id': '1b65ffd56c00259062376b2b02582f71',
  'guidislink': False,
  'authors': [{'name': 'Dana KhraicheKateryna Kadabashy'}],
  'author': 'Dana KhraicheKateryna Kadabashy',
  'author_detail': {'name': 'Dana KhraicheKateryna Kadabashy'},
  'published': 'Sat, 28 Mar 2026 07:29:02 GMT',
  'published_parsed': time.struct_time(tm_year=2026, tm_mon=3, tm_mday=28, tm_hour=7, tm_min=29, tm_sec=2, tm_wday=5, tm_yday=87, tm_isdst=0),
  'media_content': [{'medium': 'image',
    'url': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/irDf70dDnFOE/v1/1200x800.jpg'}]},
 {'title': 'Iran War Live Updates: Iranian Strike on Saudi Base Injures 12 U.S. Troops, Officials Say',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': 'https://rss.app/feeds/tA3pNMK5UFhgzWBe.xml',
   'value': 'Iran War Live Updates: Iranian Strike on Saudi Base Injures 12 U.S. Troops, Officials Say'},

In [71]:
df

,title,link,published,summary
0,Iran-backed Houthis claim missile launch on Is...,https://www.theglobeandmail.com/business/artic...,"Sat, 28 Mar 2026 11:23:02 GMT","<div><img src=""https://www.theglobeandmail.com..."
1,How the US and Israel are making the Islamic r...,https://www.aljazeera.com/opinions/2026/3/28/h...,"Sat, 28 Mar 2026 11:12:32 GMT","<div><img src=""https://www.aljazeera.com/wp-co..."
2,Iran-US war latest: Yemen’s Tehran-backed Hout...,https://www.independent.co.uk/news/world/middl...,"Sat, 28 Mar 2026 10:15:44 GMT","<div><img src=""https://static.independent.co.u..."
3,Iran-backed Houthis fire missile at Israel fro...,https://www.nbcnews.com/world/iran/iran-backed...,"Sat, 28 Mar 2026 10:12:01 GMT","<div><img src=""https://media-cldnry.s-nbcnews...."
4,Iran-backed Houthis claim first missile launch...,https://www.newsday.com/news/nation/iran-us-is...,"Sat, 28 Mar 2026 09:27:05 GMT","<div><img src=""https://cdn.newsday.com/ace/c:Y..."
5,No end to war in sight after one month as Iran...,https://www.nbcnews.com/world/iran/one-month-i...,"Sat, 28 Mar 2026 08:26:39 GMT","<div><img src=""https://media-cldnry.s-nbcnews...."
6,US-Israel war on Iran: What’s happening on day...,https://www.aljazeera.com/news/2026/3/28/iran-...,"Sat, 28 Mar 2026 08:17:54 GMT","<div><img src=""https://www.aljazeera.com/wp-co..."
7,The Iran War Is Testing Israel’s Special Relat...,https://www.bloomberg.com/news/newsletters/202...,"Sat, 28 Mar 2026 08:00:01 GMT","<div><img src=""https://assets.bwbx.io/images/u..."
8,Yemen’s Houthis claim responsibility for a mis...,https://www.aljazeera.com/news/2026/3/28/yemen...,"Sat, 28 Mar 2026 07:30:45 GMT","<div><img src=""https://www.aljazeera.com/wp-co..."
9,"Houthis Enter War and Say Attacks on Iran, Hez...",https://www.bloomberg.com/news/articles/2026-0...,"Sat, 28 Mar 2026 07:29:02 GMT","<div><img src=""https://assets.bwbx.io/images/u..."
10,Iran War Live Updates: Iranian Strike on Saudi...,https://www.nytimes.com/live/2026/03/28/world/...,"Sat, 28 Mar 2026 06:49:21 GMT","<div><img src=""https://static01.nyt.com/images..."
11,Gaza peace doubts deepen as attention shifts t...,https://www.bbc.com/news/articles/crr10v5p7lgo,"Sat, 28 Mar 2026 06:00:37 GMT","<div><img src=""https://ichef.bbci.co.uk/news/1..."
12,"1 Month On, Where US-Israel War On Iran Stands...",https://www.ndtv.com/world-news/iran-war-1-mon...,"Sat, 28 Mar 2026 05:00:28 GMT","<div><img src=""https://c.ndtvimg.com/2026-03/t..."
13,Gulf countries warn of rising threat from Iran...,https://www.theguardian.com/world/2026/mar/28/...,"Sat, 28 Mar 2026 05:00:19 GMT","<div><img src=""https://i.guim.co.uk/img/media/..."
14,Rubio sees US action in Iran completed in week...,https://www.reuters.com/world/asia-pacific/rub...,"Sat, 28 Mar 2026 04:27:21 GMT","<div><img src=""https://www.reuters.com/resizer..."
15,How the US-Israel war on Iran unfolded in its ...,https://www.aljazeera.com/news/2026/3/28/how-t...,"Sat, 28 Mar 2026 04:15:55 GMT","<div><img src=""https://www.aljazeera.com/wp-co..."
16,"Israel identifies missile launched from Yemen,...",https://www.cnn.com/2026/03/28/world/live-news...,"Sat, 28 Mar 2026 04:13:01 GMT","<div><img src=""https://media.cnn.com/api/v1/im..."
17,"Iran war: Houthis claim attack on Israel, Zele...",https://www.dw.com/en/iran-war-houthis-claim-a...,"Sat, 28 Mar 2026 02:58:06 GMT","<div><img src=""https://static.dw.com/image/765..."
18,Iran war: Houthis claim attack on Israel,https://www.dw.com/en/iran-war-houthis-claim-a...,"Sat, 28 Mar 2026 02:58:06 GMT","<div><img src=""https://static.dw.com/image/765..."
19,What we know on Day 29 of the US and Israel’s ...,https://www.cnn.com/2026/03/27/middleeast/us-i...,"Sat, 28 Mar 2026 02:44:43 GMT","<div><img src=""https://media.cnn.com/api/v1/im..."
20,Middle East crisis live: Rubio claims war expe...,https://www.theguardian.com/world/live/2026/ma...,"Sat, 28 Mar 2026 02:34:17 GMT",Iran has kept firing missiles at Israel and Gu...
21,"Iran Update Special Report, March 27, 2026",https://understandingwar.org/research/middle-e...,"Sat, 28 Mar 2026 02:26:08 GMT","<div><img src=""https://understandingwar.org/wp..."
22,Iran-Israel war LIVE: Israel military says str...,https://www.thehindu.com/news/international/ir...,"Sat, 28 Mar 2026 02:15:38 GMT","<div><img src=""https://th-i.thgim.com/public/i..."
23,Live updates: Israel stops missile fired from ...,https://apnews.com/live/iran-war-israel-trump-...,"Sat, 28 Mar 2026 02:12:00 GMT","<div><img src=""https://dims.apnews.com/dims4/d..."
24,Iran war latest: At least 12 more US troops wo...,https://www.thetimes.com/us/news-today/article...,"Sat, 28 Mar 2026 02:05:00 GMT","<div><img src=""https://www.thetimes.com/images..."

In [73]:
import feedparser
import pandas as pd
from datetime import datetime

RSS_URL = "https://news.google.com/rss/search?q=Trump+OR+Netanyahu+OR+Iran&hl=en-US&gl=US&ceid=US:en"

def fetch_rss():
    feed = feedparser.parse(RSS_URL)

    articles = []

    for entry in feed.entries:
        articles.append({
            "title": entry.title,
            "link": entry.link,
            "published": entry.published,
            "published_dt": datetime(*entry.published_parsed[:6])
        })

    df = pd.DataFrame(articles)
    return df

df = fetch_rss()
df

,title,link,published,published_dt
0,"Finally, Donald Trump has realised he’s been p...",https://news.google.com/rss/articles/CBMimgFBV...,"Fri, 27 Mar 2026 09:32:00 GMT",2026-03-27 09:32:00
1,"""They'll get mowed down"": Trump rebuffed Netan...",https://news.google.com/rss/articles/CBMie0FVX...,"Thu, 26 Mar 2026 03:04:31 GMT",2026-03-26 03:04:31
2,Israel’s War With Iran Will End When Trump Say...,https://news.google.com/rss/articles/CBMiekFVX...,"Fri, 27 Mar 2026 05:00:00 GMT",2026-03-27 05:00:00
3,"Trump, fearing slaughter, said to have rejecte...",https://news.google.com/rss/articles/CBMixAFBV...,"Thu, 26 Mar 2026 03:15:00 GMT",2026-03-26 03:15:00
4,Netanyahu Went to War With Iran While Relying ...,https://news.google.com/rss/articles/CBMikAJBV...,"Wed, 25 Mar 2026 21:23:00 GMT",2026-03-25 21:23:00
...,...,...,...,...
95,Israel attacks major industrial and nuclear si...,https://news.google.com/rss/articles/CBMirAFBV...,"Fri, 27 Mar 2026 20:50:09 GMT",2026-03-27 20:50:09
96,Chicago’s ICE playbook spreads as cities chall...,https://news.google.com/rss/articles/CBMitwFBV...,"Sat, 28 Mar 2026 11:00:00 GMT",2026-03-28 11:00:00
97,White House launches app touting Trump's recor...,https://news.google.com/rss/articles/CBMihgFBV...,"Fri, 27 Mar 2026 18:44:40 GMT",2026-03-27 18:44:40
98,Trump provides new aid for farmers and food su...,https://news.google.com/rss/articles/CBMikgFBV...,"Fri, 27 Mar 2026 21:25:00 GMT",2026-03-27 21:25:00
99,Opinion | Why a Long War Helps Iran - The New ...,https://news.google.com/rss/articles/CBMid0FVX...,"Sat, 28 Mar 2026 11:00:13 GMT",2026-03-28 11:00:13

In [74]:
keywords = ["Trump", "Netanyahu", "Iran"]

df_filtered = df[df["title"].str.contains("|".join(keywords), case=False, na=False)]

print(df_filtered)

                                                title  \
0   Finally, Donald Trump has realised he’s been p...
1   "They'll get mowed down": Trump rebuffed Netan...
2   Israel’s War With Iran Will End When Trump Say...
3   Trump, fearing slaughter, said to have rejecte...
4   Netanyahu Went to War With Iran While Relying ...
..                                                ...
95  Israel attacks major industrial and nuclear si...
96  Chicago’s ICE playbook spreads as cities chall...
97  White House launches app touting Trump's recor...
98  Trump provides new aid for farmers and food su...
99  Opinion | Why a Long War Helps Iran - The New ...

                                                 link  \
0   https://news.google.com/rss/articles/CBMimgFBV...
1   https://news.google.com/rss/articles/CBMie0FVX...
2   https://news.google.com/rss/articles/CBMiekFVX...
3   https://news.google.com/rss/articles/CBMixAFBV...
4   https://news.google.com/rss/articles/CBMikAJBV...
..                                                ...
95  https://news.google.com/rss/articles/CBMirAFBV...
96  https://news.google.com/rss/articles/CBMitwFBV...
97  https://news.google.com/rss/articles/CBMihgFBV...
98  https://news.google.com/rss/articles/CBMikgFBV...
99  https://news.google.com/rss/articles/CBMid0FVX...

                        published        published_dt
0   Fri, 27 Mar 2026 09:32:00 GMT 2026-03-27 09:32:00
1   Thu, 26 Mar 2026 03:04:31 GMT 2026-03-26 03:04:31
2   Fri, 27 Mar 2026 05:00:00 GMT 2026-03-27 05:00:00
3   Thu, 26 Mar 2026 03:15:00 GMT 2026-03-26 03:15:00
4   Wed, 25 Mar 2026 21:23:00 GMT 2026-03-25 21:23:00
..                            ...                 ...
95  Fri, 27 Mar 2026 20:50:09 GMT 2026-03-27 20:50:09
96  Sat, 28 Mar 2026 11:00:00 GMT 2026-03-28 11:00:00
97  Fri, 27 Mar 2026 18:44:40 GMT 2026-03-27 18:44:40
98  Fri, 27 Mar 2026 21:25:00 GMT 2026-03-27 21:25:00
99  Sat, 28 Mar 2026 11:00:13 GMT 2026-03-28 11:00:13

[92 rows x 4 columns]

In [ ]:
import feedparser
import pandas as pd
from datetime import datetime
import time
from textblob import TextBlob

# 🔗 RSS SOURCE (Google News — real-time enough)
RSS_URL = "https://news.google.com/rss/search?q=Trump+Netanyahu+Iran&hl=en-US&gl=US&ceid=US:en"

KEYWORDS = ["Trump", "Netanyahu", "Iran"]

# 🟢 1. FETCH DATA
def fetch_rss():
    feed = feedparser.parse(RSS_URL)

    articles = []

    for entry in feed.entries:
        articles.append({
            "title": entry.title,
            "link": entry.link,
            "published": entry.published,
            "published_dt": datetime(*entry.published_parsed[:6])
        })

    df = pd.DataFrame(articles)
    return df


# 🟢 2. FILTER POLITICAL SIGNALS
def filter_keywords(df):
    return df[df["title"].str.contains("|".join(KEYWORDS), case=False, na=False)]


# 🟢 3. FORMAT TIMESTAMP
def format_time(df):
    df["published_dt"] = pd.to_datetime(df["published_dt"])
    df["formatted_time"] = df["published_dt"].dt.strftime("%m/%d/%Y %H:%M")
    return df


# 🟢 4. SENTIMENT (FAST VERSION)
def get_sentiment(text):
    score = TextBlob(text).sentiment.polarity  # -1 to 1
    return int(score * 100)  # convert to -100 to 100


def add_sentiment(df):
    df["sentiment_score"] = df["title"].apply(get_sentiment)
    return df


# 🟢 5. MAP TO YOUR JSON FORMAT
def to_signal_json(df):
    signals = []

    for _, row in df.iterrows():
        signals.append({
            "source": "politician",
            "sentiment_score": row["sentiment_score"],
            "confidence": 70,  # placeholder
            "signal": row["title"],
            "author": "unknown",
            "platform": "rss",
            "tier": "major",
            "event_location": {
                "city": None,
                "country": None,
                "lat": None,
                "lon": None
            },
            "timestamp": row["published_dt"].isoformat()
        })

    return signals


# 🟢 6. MAIN LOOP (REAL-TIME SIMULATION)
def run_pipeline():
    df = fetch_rss()

    if df.empty:
        print("⚠️ No data fetched")
        return

    df = filter_keywords(df)

    if df.empty:
        print("⚠️ No matching political news")
        return

    df = format_time(df)
    df = add_sentiment(df)

    print("\n🟢 LIVE POLITICAL SIGNALS:\n")
    print(df[["title", "formatted_time", "sentiment_score"]].head())

    signals = to_signal_json(df)

    print("\n📡 JSON OUTPUT (for Central Hub):\n")
    for s in signals[:3]:
        print(s)


# 🔁 LOOP EVERY 60 SECONDS
while True:
    run_pipeline()
    time.sleep(60)

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):

{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Finally, Donald Trump has realised he’s been played by Israel - the-independent.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T09:32:00'}
{'source': 'politician', 'sentiment_score': -15, 'confidence': 70, 'signal': '"They\'ll get mowed down": Trump rebuffed Netanyahu idea to call for Iran uprising - Axios', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-26T03:04:31'}
{'source': 'politician', 'sentiment_score': 0, 'confidence': 70, 'signal': 'Israel’s War With Iran Will End When Trump Says Stop - Bloomberg.com', 'author': 'unknown', 'platform': 'rss', 'tier': 'major', 'event_location': {'city': None, 'country': None, 'lat': None, 'lon': None}, 'timestamp': '2026-03-27T05:00:00'}

🟢 LIVE POLITICAL SIGNALS:

                                               title    formatted_time  \
0  Finally, Donald Trump has realised he’s been p...  03/27/2026 09:32
1  "They'll get mowed down": Trump rebuffed Netan...  03/26/2026 03:04
2  Israel’s War With Iran Will End When Trump Say...  03/27/2026 05:00
3  Trump, fearing slaughter, said to have rejecte...  03/26/2026 03:15
4  Netanyahu Went to War With Iran While Relying ...  03/25/2026 21:23

   sentiment_score
0                0
1              -15
2                0
3                0
4                0

📡 JSON OUTPUT (for Central Hub):
